slices:
  - sources:
      - model: ajibawa-2023/Code-Llama-3-8B
        layer_range: [0, 32]
      - model: defog/llama-3-sqlcoder-8b
        layer_range: [0, 32]
merge_method: slerp
base_model: ajibawa-2023/Code-Llama-3-8B
parameters:
  t:
    - filter: self_attn
      value: [0, 0.3, 0.5, 0.7, 0.5]
    - filter: mlp
      value: [0, 0.3, 0.5, 0.7, 0.5]
    - value: 0.4 # fallback for rest of tensors
dtype: bfloat16